### ISSUE TITLE
Mac Installation Error. - node 0.12.0

### ISSUE THREAD

**Issue by meronhunter** [sandeepmistry/noble#142]
Hi, Thank you for your hard work,

I am trying to install noble, but it gives me an error with:
Failed at the noble@0.3.9 install script 'node install.js'.
"npm ERR! This is most likely a problem with the noble package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls noble
npm ERR! There is likely additional logging output above."

My Node version is 0.12.0 and my computer OS is mac, most recent version.

If there is a way to fix this please let me know :)

Thanks

**Comment by sandeepmistry** [comment]
@meronhunter could you please provide the ```npm-debug.log``` file?

I think it's failing because node-xpc-connection doesn't support 0.12 yet, but would like to confirm.

Anyways, I've published a new version of node-xpc-connection, that uses the latest ```nan``` so try again, I expect it to work: https://github.com/sandeepmistry/node-xpc-connection/commit/3bd77657198b1f688fffd63b03b95e93946ad1a7
