### ISSUE TITLE
Reason for not using built-in bluetooth capabilities in Windows?

### ISSUE THREAD

**Issue by pchandramouli** [sandeepmistry/noble#493]
I'm trying out noble as part of a PoC. Noticed as part of Prerequisites that it requires Compatible Bluetooth 4.0 USB adapter (aka. "dongle").

Can you throw light on why is it so - won't it be able to use Windows built-in driver and the systems default bluetooth hardware? Is it specific to noble or does it have something to do with Windows itself? (I've seen bluetooth mice requiring a compatible dongle, and hence my question on whether it's a limitation in Windows itself.)

**Comment by Nikolay-Kha** [comment]
Bluetooth low energy(aka BLE, Bluetooth smart) appear since Bluetooth 4.0 specification. Moreover, dongles with classic bluetooth 4.0 may not support BLE according to the specification, but practically I haven't seen such dongles - all of them supports both classic Bluetooth and BLE.

noble or any other software anyway use system driver for access at least to HCI part of Bluetooth. So I don't get the idea of using windows driver.

**Comment by sandeepmistry** [comment]
@pchandramouli there's a fairly lengthy discussion in #84. 

To summarize, Windows didn't really have great BLE support until Windows 10, and the current versions of Windows requires peripherals to support pairing (https://github.com/sandeepmistry/noble/issues/84#issuecomment-181138951). 

@hgwood's made a Windows 10 specific binding here: https://github.com/hgwood/winble - but it requires Chakra core instead of v8 (as well as requires pairing).
