### ISSUE TITLE
No compatible USB Bluetooth 4.0 device found

### ISSUE THREAD

**Issue by AzertyUser** [sandeepmistry/noble#570]
Keep getting this error. But I do find the device in bluetoothsection of windows. I'm using a usb dongle. 

![image](https://cloud.githubusercontent.com/assets/26420713/23999499/e8f71ee2-0a58-11e7-9fcf-d2826deacd70.png)

**Comment by ericblade** [comment]
Also running into this on a PC that has no Bluetooth adapter -- lack of functionality probably shouldn't cause a throw inside a require.  I can't think of any other library I've ever seen that throws while it's being loaded.  Of course, it can easily be worked around, but

`try {
    noble = require("noble");
} catch(err) {
    noble = {
        on: () => {},
    };
}`

is particularly ugly.  I would expect that it might warn, not throw, and just not do anything.

**Comment by sandeepmistry** [comment]
@AzertyUser please see: https://github.com/sandeepmistry/noble#windows

@ericblade feel free to PR a suggestion to change the behaviour.

**Comment by jayalfredprufrock** [comment]
I have to agree with @ericblade . I was surprised to find my program completely crash just because a particular computer hadn't gone through the complicated usb bluetooth adapter install process. I thought I was surely missing something until I discovered this issue. What happens on OSX if the computer doesn't have a bluetooth adapter? I assumed that the "poweredOn" state change event just never fires, but now I'm not so sure...
